//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Iterator.java
//  @ Date : 02/11/2009
//  @ Author : 
//
//




/** */
public class Iterator
{
	/** */
	public boolean hasNext()
	{
	
	}
	
	/** */
	public boolean getNext()
	{
	
	}
	
	/** */
	public int position()
	{
	
	}
	
	/** */
	public int skipToSet()
	{
	
	}
	
	/** */
	public int skipToUnset()
	{
	
	}
}
