//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VectorBit.java
//  @ Date : 08/11/2009
//  @ Author : 
//
//




/** */
public class VectorBit
{
	/** */
	public boolean test(int indice)
	{
	
	}
	
	/** */
	public boolean set(int indice)
	{
	
	}
	
	/** */
	public boolean unset(int indice)
	{
	
	}
	
	/** */
	public boolean negar(int indice)
	{
	
	}
	
	/** */
	public void or(VectorBit bs)
	{
	
	}
	
	/** */
	public void xor(VectorBit bs)
	{
	
	}
	
	/** */
	public void copiar(VectorBit )
	{
	
	}
	
	/** */
	public void iterator()
	{
	
	}
	
	/** */
	public void builder()
	{
	
	}
	
	/** */
	public String toString()
	{
	
	}
}
